# Generated by Django 5.1.7 on 2025-03-25 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.PositiveSmallIntegerField(choices=[(1, 'Period 1'), (2, 'Period 2'), (3, 'Period 3'), (4, 'Period 4'), (5, 'Period 5'), (6, 'Period 6'), (7, 'Period 7'), (8, 'Period 8')], help_text='Period number (1-8)')),
                ('class_name', models.CharField(choices=[('nursery', 'Nursery'), ('lkg', 'LKG'), ('ukg', 'UKG'), ('1', 'Class 1'), ('2', 'Class 2'), ('3', 'Class 3'), ('4', 'Class 4'), ('5', 'Class 5'), ('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12')], help_text='Class (Nursery-12)', max_length=10)),
                ('subject', models.CharField(help_text='Subject taught during this period', max_length=100)),
                ('time_start', models.TimeField(help_text='Start time of the period (e.g., 09:00 AM)')),
                ('time_end', models.TimeField(help_text='End time of the period (e.g., 09:40 AM)')),
                ('is_active', models.BooleanField(default=True, help_text='Is this timetable entry active?')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='staff.teachingstaff')),
            ],
            options={
                'verbose_name': 'Timetable Entry',
                'verbose_name_plural': 'Timetable',
                'ordering': ['class_name', 'period'],
                'unique_together': {('period', 'class_name', 'time_start', 'teacher')},
            },
        ),
    ]
