# Generated by Django 5.2.1 on 2025-06-07 06:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherstaff',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachingstaff',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachingstaff',
            name='experience',
            field=models.PositiveIntegerField(blank=True, help_text='Years of teaching experience', null=True),
        ),
        migrations.AddField(
            model_name='teachingstaffsubject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='joining_date',
            field=models.DateField(default=models.DateField(auto_now_add=True), help_text='Date when the staff joined'),
        ),
    ]
