# Generated by Django 5.2.1 on 2025-06-07 06:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdocument',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Document', 'verbose_name_plural': 'User Documents'},
        ),
        migrations.RenameField(
            model_name='userdocument',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='familymember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
