# Generated by Django 5.1.7 on 2025-03-25 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdocument',
            name='version_s3',
        ),
    ]
