# Generated by Django 5.2.3 on 2025-07-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userdocument_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
