# Generated by Django 5.1.7 on 2025-03-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_family_familymember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdocument',
            name='document_context',
            field=models.CharField(choices=[('student_admission', 'Student Admission'), ('staff_certification', 'Staff Certification'), ('previous_institution', 'Previous Institution'), ('rte', 'Right to Education (RTE)'), ('general', 'General')], default='general', max_length=50),
        ),
    ]
