# Generated by Django 5.1.7 on 2025-04-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_blood_group_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
