# Generated by Django 5.1.7 on 2025-04-02 12:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_occupation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['-created_at'], 'verbose_name': 'Family', 'verbose_name_plural': 'Families'},
        ),
        migrations.AddField(
            model_name='family',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
