# Generated by Django 5.2.1 on 2025-06-07 06:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when item was paid', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Batch purchase date'),
        ),
    ]
