# Generated by Django 5.1.7 on 2025-03-25 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='Amount of discount given', max_digits=12)),
                ('discount_type', models.CharField(choices=[('RTE_DISCOUNT', 'RTE Discount'), ('GENERAL_DISCOUNT', 'General Discount')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discount_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts_given', to=settings.AUTH_USER_MODEL)),
                ('payment_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='finance.paymenttransaction')),
            ],
        ),
    ]
