# Generated by Django 5.1.7 on 2025-03-25 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_discount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Details of the expense')),
                ('expense_category', models.CharField(choices=[('SALARY', 'Salary'), ('UTILITY', 'Utility'), ('MAINTENANCE', 'Maintenance'), ('MISC', 'Miscellaneous'), ('SUPPLIES', 'Supplies'), ('TRANSPORT', 'Transport')], max_length=50)),
                ('date', models.DateField(help_text='Date of the expense')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='finance.paymenttransaction')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
