# Generated by Django 5.2.1 on 2025-06-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_ledgeraccounttype_created_at_wallettransaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementexpense',
            name='date',
            field=models.DateTimeField(help_text='Date of the expense'),
        ),
    ]
