# Generated by Django 5.2.1 on 2025-06-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_managementexpense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='managementexpense',
            name='date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date of the expense'),
        ),
    ]
