# Generated by Django 5.1.7 on 2025-03-31 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_paymentreceipt_delete_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managementexpense',
            old_name='transaction',
            new_name='payment_transaction',
        ),
        migrations.RenameField(
            model_name='wallettransaction',
            old_name='transaction_id',
            new_name='payment_transaction',
        ),
    ]
