# Generated by Django 5.1.7 on 2025-03-31 09:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_rename_transaction_managementexpense_payment_transaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentReceipt',
            new_name='PaymentSummary',
        ),
    ]
