# Generated by Django 5.1.7 on 2025-03-31 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_blood_group_alter_user_gender'),
        ('finance', '0007_rename_paymentreceipt_paymentsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='core.family'),
        ),
    ]
