# Generated by Django 5.1.7 on 2025-04-02 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_wallettransaction_family'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentsummary',
            options={'ordering': ['-date'], 'verbose_name': 'Payment Summary', 'verbose_name_plural': 'Payment Summaries'},
        ),
    ]
