# Generated by Django 5.1.7 on 2025-03-25 12:46

import apps.students.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(help_text='Height in cm')),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('apaar_id', models.CharField(max_length=20, unique=True)),
                ('pen_number', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(choices=[('KDIC', 'KDIC'), ('KDPV', 'KDPV')], max_length=10)),
                ('serial_number', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serials', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1)),
                ('is_rte', models.BooleanField(default=False)),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('session', models.CharField(default=apps.students.models.StudentAdmission.generate_session, help_text='e.g., 2024-2025 leave blank to set to current session', max_length=9)),
                ('student_class', models.CharField(choices=[('NUR', 'NUR'), ('LKG', 'LKG'), ('UKG', 'UKG'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], help_text='Class (e.g., 10, 12, etc.)', max_length=20)),
                ('fee_structure', models.TextField(help_text='Details about the fee structure')),
                ('total_fee', models.DecimalField(decimal_places=2, help_text='Total fee amount', max_digits=10)),
                ('no_dues', models.BooleanField(default=True)),
                ('roll_number', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('passed', 'Passed'), ('failed', 'Failed')], default='active', max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='students.student')),
                ('serial_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='students.studentserial')),
            ],
        ),
    ]
