# Generated by Django 5.2 on 2025-05-22 21:25

import apps.students.models
import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., class_6_fees', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(default=datetime.date.today, help_text='Fee structure validity start date')),
                ('end_date', models.DateField(blank=True, help_text='Fee structure validity end date', null=True)),
            ],
            options={
                'verbose_name': 'Fee Structure',
                'verbose_name_plural': 'Fee Structures',
            },
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., tuition, exam', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount for this fee type', max_digits=12)),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_types', to='students.feestructure')),
            ],
            options={
                'verbose_name': 'Fee Type',
                'verbose_name_plural': 'Fee Types',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('height', models.FloatField(blank=True, help_text='Height in cm', null=True)),
                ('weight', models.FloatField(blank=True, help_text='Weight in kg', null=True)),
                ('apaar_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('pen_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreviousInstitutionDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_institution', models.CharField(help_text='Name of the last attended institution', max_length=255)),
                ('score', models.DecimalField(decimal_places=2, help_text='Obtained marks', max_digits=7)),
                ('mm', models.DecimalField(decimal_places=2, help_text='Maximum marks', max_digits=7)),
                ('percent', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage (auto-calculated)', max_digits=5, null=True)),
                ('rte', models.BooleanField(default=False, help_text='Was the student a Right to Education (RTE) beneficiary in the previous institution ?')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='previous_institution', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAdmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1)),
                ('is_rte', models.BooleanField(default=False)),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('session', models.CharField(default=apps.students.models.StudentAdmission.generate_session, help_text='e.g., 2023-2024 leave blank to set to current session', max_length=9)),
                ('student_class', models.CharField(choices=[('NUR', 'NUR'), ('LKG', 'LKG'), ('UKG', 'UKG'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], help_text='Class (e.g., 10, 12, etc.)', max_length=20)),
                ('total_fee', models.DecimalField(decimal_places=2, help_text='Total fee amount', max_digits=10)),
                ('no_dues', models.BooleanField(default=False)),
                ('roll_number', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('passed', 'Passed'), ('failed', 'Failed'), ('dropped', 'Dropped'), ('graduated', 'Graduated')], default='active', max_length=10)),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_admissions', to='students.feestructure')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='FeeDue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Due amount', max_digits=12)),
                ('paid', models.BooleanField(default=False, help_text='Has this fee been paid?')),
                ('paid_at', models.DateTimeField(blank=True, help_text='Timestamp when fee was paid', null=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_dues', to='finance.paymenttransaction')),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_dues', to='students.feetype')),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_dues', to='students.studentadmission')),
            ],
            options={
                'verbose_name': 'Fee Due',
                'verbose_name_plural': 'Fee Dues',
            },
        ),
        migrations.CreateModel(
            name='StudentSerial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_name', models.CharField(choices=[('KDIC', 'KDIC'), ('KDPV', 'KDPV')], max_length=10)),
                ('serial_number', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serials', to='students.student')),
            ],
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='serial_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='students.studentserial'),
        ),
    ]
