# Generated by Django 5.2.4 on 2025-09-06 13:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_feetype_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='previousinstitutiondetail',
            name='passing_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year of passing', null=True),
        ),
        migrations.CreateModel(
            name='BoardAcademicDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_class', models.PositiveIntegerField(help_text='Class')),
                ('roll_no', models.PositiveIntegerField(help_text='Roll number')),
                ('board', models.CharField(help_text='Board name', max_length=255)),
                ('school', models.CharField(help_text='School name', max_length=255)),
                ('passing_year', models.PositiveIntegerField(help_text='Year of passing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_academic_details', to='students.student')),
            ],
        ),
    ]
