# Generated by Django 5.1.7 on 2025-03-25 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_discount'),
        ('students', '0002_alter_studentadmission_no_dues_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., class_6_fees', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(help_text='Fee structure validity start date')),
                ('end_date', models.DateField(help_text='Fee structure validity end date')),
            ],
            options={
                'verbose_name': 'Fee Structure',
                'verbose_name_plural': 'Fee Structures',
            },
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., tuition, exam', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount for this fee type', max_digits=12)),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_types', to='students.feestructure')),
            ],
            options={
                'verbose_name': 'Fee Type',
                'verbose_name_plural': 'Fee Types',
            },
        ),
        migrations.CreateModel(
            name='FeeDue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Due amount', max_digits=12)),
                ('paid', models.BooleanField(default=False, help_text='Has this fee been paid?')),
                ('paid_at', models.DateTimeField(blank=True, help_text='Timestamp when fee was paid', null=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_dues', to='students.studentadmission')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_dues', to='finance.paymenttransaction')),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_dues', to='students.feetype')),
            ],
            options={
                'verbose_name': 'Fee Due',
                'verbose_name_plural': 'Fee Dues',
            },
        ),
    ]
