# Generated by Django 5.2.4 on 2025-09-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_previousinstitutiondetail_passing_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardacademicdetails',
            name='is_passed',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
