# Generated by Django 5.1.7 on 2025-03-27 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_feestructure_feetype_feedue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='end_date',
            field=models.DateField(blank=True, help_text='Fee structure validity end date', null=True),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='name',
            field=models.CharField(help_text='e.g., class_6_fees', max_length=255),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now, help_text='Fee structure validity start date'),
        ),
        migrations.AlterField(
            model_name='previousinstitutiondetail',
            name='rte',
            field=models.BooleanField(default=False, help_text='Was the student a Right to Education (RTE) beneficiary in the previous institution ?'),
        ),
    ]
