# Generated by Django 5.2.4 on 2025-09-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_boardacademicdetails_is_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardacademicdetails',
            name='mm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum marks', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='boardacademicdetails',
            name='percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage (auto-calculated)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='boardacademicdetails',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Obtained marks', max_digits=7, null=True),
        ),
    ]
