# Generated by Django 5.1.7 on 2025-03-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_feestructure_end_date_alter_feestructure_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='apaar_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='height',
            field=models.FloatField(blank=True, help_text='Height in cm', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='pen_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight in kg', null=True),
        ),
    ]
