# Generated by Django 5.2.4 on 2025-09-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_boardacademicdetails_mm_boardacademicdetails_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardacademicdetails',
            name='subject_group',
            field=models.CharField(blank=True, help_text='Subjects: write names of the subjects with comma separated', max_length=255, null=True),
        ),
    ]
