# Generated by Django 5.1.7 on 2025-03-28 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_apaar_id_alter_student_height_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='previousinstitutiondetail',
            old_name='last_institution',
            new_name='previous_institution',
        ),
    ]
