# Generated by Django 5.2.4 on 2025-09-07 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_subjects_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentadmission',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.courses'),
        ),
    ]
