# Generated by Django 5.2 on 2025-04-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_feestructure_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentadmission',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('passed', 'Passed'), ('failed', 'Failed'), ('dropped', 'Dropped'), ('graduated', 'Graduated')], default='active', max_length=10),
        ),
    ]
