# Generated by Django 5.2.4 on 2025-09-10 17:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_session_alter_studentadmission_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, help_text="Optional extra info, e.g., 'Monthly-1'", max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='students.session')),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='students.examtype')),
            ],
            options={
                'unique_together': {('exam_type', 'session')},
            },
        ),
        migrations.CreateModel(
            name='ExamCourseSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mm', models.DecimalField(decimal_places=2, help_text='Maximum marks', max_digits=7)),
                ('course_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_subjects', to='students.coursesubject')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subjects', to='students.exam')),
            ],
            options={
                'unique_together': {('exam', 'course_subject')},
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, help_text='Obtained marks', max_digits=7)),
                ('percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('exam_course_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='students.examcoursesubject')),
                ('student_admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='students.studentadmission')),
            ],
            options={
                'unique_together': {('student_admission', 'exam_course_subject')},
            },
        ),
    ]
