# Generated by Django 5.2.4 on 2025-09-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_examtype_exam_examcoursesubject_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
    ]
