# Generated by Django 5.2.4 on 2025-09-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_course_description_alter_subject_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='applicable_for',
            field=models.CharField(blank=True, choices=[('NUR', 'NUR'), ('LKG', 'LKG'), ('UKG', 'UKG'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], help_text='Class (e.g., 10, 12, etc.)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
