# Generated by Django 5.2.4 on 2025-09-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_course_applicable_for_alter_course_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage (auto-calculated)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Obtained marks', max_digits=7, null=True),
        ),
    ]
