# Generated by Django 5.2.4 on 2025-09-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_alter_score_percent_alter_score_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
