# Generated by Django 5.2.12 on 2026-03-10 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_exam_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together=set(),
        ),
    ]
